"""Wavin Sentio over Modbus TCP, built on modbus_event_connect."""
from ._model import (
    PERIPHERAL,
    ROOM,
    SENTIO,
    UNITS,
    BlockingSource,
    LocationPointKey,
    PeripheralPointKey,
    PeripheralType,
    PointKey,
    RoomLock,
    RoomPointKey,
    RoomState,
    RoomType,
    peripheral_key,
    room_key,
)
from ._sentio import (
    DEFAULT_PORT,
    DEFAULT_UNIT_ID,
    SentioPeripheral,
    SentioRoom,
    create_client,
    create_client_on,
    peripherals,
    rooms,
)

__version__ = "0.2.0rc1"
__all__ = [
    "DEFAULT_PORT",
    "DEFAULT_UNIT_ID",
    "PERIPHERAL",
    "ROOM",
    "SENTIO",
    "UNITS",
    "BlockingSource",
    "LocationPointKey",
    "PeripheralPointKey",
    "PeripheralType",
    "PointKey",
    "RoomLock",
    "RoomPointKey",
    "RoomState",
    "RoomType",
    "SentioPeripheral",
    "SentioRoom",
    "create_client",
    "create_client_on",
    "peripheral_key",
    "peripherals",
    "room_key",
    "rooms",
]
